### ISSUE TITLE
idom317 causes jenkins to fai

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion-idioms#170]
I get this when I run this example
```
 > ./bin/check_example_jvm.sh webserver/idioms/src/idiom317ex.fz
RUN webserver/idioms/src/idiom317ex.fz 1c1,3
< gwVTD0SEcmDroR8dWvRaON1ULTy3D4lbHY3iVl3NQGVkhrIUwx
---
> W2ztMKerlpb7QvNKXIaaz3lqY4k6fBv9UJ2Iba1jPIAxnYWGWP
> u4krOwuUWYXS9giTiNiUQrrSGVthdbV6hjb9nNLdkpfXpCozl6
> NWWwFf4vJ54mxNdRuIrv8HDvLkoVLv5lWiB7HE46dDo13aQgA3
*** FAILED out on webserver/idioms/src/idiom317ex.fz

```
There are apparently two problems:

- the example prints three line, the expected_out, however, contains only one line of data
- the output are random strings, I suggest to add a `skip` file to ignore this in jenkins (describe the reason why whinin the skip file).

**Comment by michaellilltokiwa** [comment]
@fridis This is strange since a fixed seed is used with simple_random.

**Comment by fridis** [comment]
> @fridis This is strange since a fixed seed is used with simple_random.

You are right, I missed that. Than, only the expected output needs to be updated.
